[package]
name = "weatherAlert"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
rusqlite = { version = "0.33.0" }
serde_json = { version = "1.0.139" }